### ISSUE TITLE
property styles

### ISSUE THREAD

**Issue by misterfourtytwo** [daohoangson/flutter_widget_from_html#367]
would be real nice to add property styles to element in custom styles builder so people won't need to write smth like this every time they need to parse style properties
```[dart]
          final List<String> l = e?.attributes['style']
                  ?.replaceAll(RegExp(r'(\s)+'), '')
                  ?.split(';') ??
              <String>[];

          final Map<String, String> styles = <String, String>{};
          for (final String keyValue
              in l.where((String value) => value?.contains(':') == true)) {
            final List<String> pair =
                keyValue.replaceAll(RegExp(r'([\s]+)'), ' ').split(':');
            styles[pair[0]] = pair[1];
          }
```

**Comment by daohoangson** [comment]
Why do you need to parse the `styles` atttibute  in `customStylesBuilder`? The package automatically parses those and apply to the element by itself already...

**Comment by misterfourtytwo** [comment]
when i need to apply changes to incoming styles.
i.e. there is a company site, api sends some page parts to render in app, but i need to change some styling

**Comment by daohoangson** [comment]
Ah I see, it's possible we will make the parsed key-value pairs available during `customStylesBuilder` for your use case.

**Comment by daohoangson** [comment]
Version `0.5.2` has been released with support for this. It is now straightforward to get the list of inline styles:

```dart
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';

/// in your `WidgetFactory` or `BuildOp`
for (final style in meta.element.styles) {
  print('${style.key}=${style.value}');
}
```

Please try upgrading and let me know whether it works for you. Thank you.

**Comment by misterfourtytwo** [comment]
as far as i understand i cannot use this in the custom styles builder?

**Comment by daohoangson** [comment]
No problem, you can use it in `customStylesBuilder`. Something like this:

```dart
          HtmlWidget(
            html,
            customStylesBuilder: (element) {
              for (final style in element.styles) {
                if (style.key == 'foo') {
                  return {'foo': 'bar'};
                }
              }

              return null;
            },
          ),
```

**Comment by misterfourtytwo** [comment]
so, you can see that my app has last plugin version locked:
<img width="283" alt="image" src="https://user-images.githubusercontent.com/17276509/108689142-c5494180-7509-11eb-8e5e-ac397d5e91a1.png">

and debugger seem not to see this field
<img width="802" alt="image" src="https://user-images.githubusercontent.com/17276509/108689772-8d8ec980-750a-11eb-90ed-5a3c0d7f7fd5.png">

**Comment by daohoangson** [comment]
It is not a field, it is an extension. Does your `print()` statement work?

**Comment by misterfourtytwo** [comment]
as i'm saying, nope.
if this is an extension, then i probably must import it separately and this solves the mystery why analyzer doesn't see it.
could u please specify where it is located so i could test with it inluded in file?

**Comment by daohoangson** [comment]
```dart
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';
```

That should be enough. If you follow that import, it will `export 'src/helpers.dart';` then `export 'package:flutter_widget_from_html_core/src/core_helpers.dart';`. You should be able to fine `DomElementExtension` there.

**Comment by misterfourtytwo** [comment]
sorry for the delay, got busy lately.
class extension is certainly there, but my project doesn't seem to connect it, even after explicitly importing extension and specifying element type.
<img width="774" alt="image" src="https://user-images.githubusercontent.com/17276509/109201073-6eb26080-77b2-11eb-87e9-2a2c70804df2.png">
when instead of prefixing type i use hide element on `'package:flutter/foundation.dart'`, i get following
<img width="490" alt="image" src="https://user-images.githubusercontent.com/17276509/109202085-a4a41480-77b3-11eb-877e-c7c5d98cb120.png">
though, without `'package:html/dom.dart'` import analyzer can not find **Element** type.
my guess is that there is some bug in analyzer/linter, which does not allow to properly import extensions from external package, but inside one everything works properly.
switched and tested on the master flutter branch, instead of current, got the same behavior.

**Comment by daohoangson** [comment]
I think I have figured it out.

In the first version of your code, you used `customStylesBuilder: (dynamic e) {}`. The `dynamic` type basically disabled the extension method since extension is resolved at compile time. Then you specified `Element` type but that didn't work because of a name conflict. You have to follow the suggestion to `import 'package:html/dom.dart' as dom;` then use `customStylesBuilder: (dom.Element e) {}`.

It's possible to skip the typing completely, using `customStylesBuilder: (e) {}` is simple and should be enough.

**Comment by misterfourtytwo** [comment]
nope, using import as dom was the first thing i did.
ill check this on my linux machine and later recheck on mac.
if one does not cast type and specify dynamic, you could still see full object type in debugger and it hadn't imported extension for me.
unfortunately, linter rules of my app do not allow to run without specified arguments types. ill also check this without them to narrow down problem cases.

**Comment by daohoangson** [comment]
I have just revisited this with Flutter 2 and it seems to work fine.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';
import 'package:html/dom.dart' as dom;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Issue 367'),
      ),
      body: HtmlWidget(
        'Foo',
        customStylesBuilder: (dom.Element element) {
          for (final style in element.styles) {
            if (style.key == 'foo') {
              return {'foo': 'bar'};
            }
          }

          return null;
        },
      ),
    );
  }
}
```

**Comment by misterfourtytwo** [comment]
Yeah, on 2.0 seems to be working fine with either of `dynamic`, `dom.Element` and simply `Element`(when hidden imports from other packages
